name: gofmt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.16
      id: go
    # Check the codebase has been formatted by `gofmt` by checking whether
    # the output of `gofmt -l` is empty, as recommended in
    # https://github.com/golang/go/issues/24230)
    - name: Run gofmt
      run: test -z $(gofmt -l .)
